apiVersion: v1
kind: Secret
metadata:
    name: podinfo-secrets
    namespace: production
type: Opaque
stringData:
    API_KEY: ENC[AES256_GCM,data:sYBPKr3IC453HdM8kT2z9NRbJbDQzynUgdMSPjY=,iv:qb//YR35T5ERM6jfzkSck1LSGE1tMHexaBL13bS5mV0=,tag:d16/Frl7Rum5JpnnvfbOJA==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:MCowlQ/Glr0CWqChMtAhMCADhOCRpRdqTyYqWg==,iv:fU4tyx7AK7W6aRbPm+3VsgCG5Dl/WBjKNjoQlwUjDgk=,tag:ZTxapvH6A0jnzhkqd5cCkA==,type:str]
sops:
    age:
        - recipient: age1x4r5557tw69dwnjv87d0lz342auelwnxf9rcrlv7fmv9jskycv9qc6ynrj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwaGFTVkRCZzcyb2c1aWxj
            NVQwRmQ2dkwrZjhRTWgzayt1anBWV1BqMEZ3CkpiSHpsQjJOYUY2OXFiTUJnQisz
            K3Y1dDh6cHg0OGRhMXNDMHcwZG12ZXcKLS0tIFR2SWtTYTRnV3F2cldYZGlGZVFH
            RWlYWkhXbThuQVRGMEtpZzExQm1hQzQKoXdOBMZRaP8GdunVLkHZbOQv3b9vCsX/
            NOjKlFZ38JP5p1KNy1lx6x2cGNIZHDKc2Oy5sTkKYeaEPDiQcEMz9g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-05T18:13:39Z"
    mac: ENC[AES256_GCM,data:5oeCuQvXRq6Bq1zkZbcw52Jku3KBHu5Lw1YKzDqIwQCPY537HoLECp3yaPqu2mQAHMGk1iqNnpAfQD7bQnOzWM6wuMnTKuTBb0Szl+BvyjU1dmpunaV9cyB6Ba6cq3NCG5i0J9d4ZQFF902O/q2XXEVyyPNRqT0MPZQckM1Qe0I=,iv:levQQFSPcjGEOpI0NTcx0QgqUbklAWaqSkieq7asaoM=,tag:JwHP18e2IW9W1OVu30KN1w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
